# Generated by Django 3.2.8 on 2021-10-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktua',
            name='kategoria',
            field=models.TextField(default='Ogia'),
            preserve_default=False,
        ),
    ]
