# Generated by Django 3.2.8 on 2021-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezuak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mezua', models.TextField()),
            ],
        ),
    ]
