# Generated by Django 3.2.8 on 2021-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0002_mezuak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mezuak',
            new_name='Mezua',
        ),
    ]
