# Generated by Django 3.2.8 on 2021-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0003_rename_mezuak_mezua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_banatzailea',
        ),
        migrations.DeleteModel(
            name='Banatzailea',
        ),
    ]
