# Generated by Django 3.2.8 on 2021-11-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0004_auto_20211116_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bezeroa',
            name='mota',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_ticket',
        ),
    ]
