# Generated by Django 3.2.8 on 2021-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0005_auto_20211116_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
