# Generated by Django 3.2.8 on 2021-11-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
