# Generated by Django 3.2.8 on 2021-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0009_auto_20211117_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='entrega_data',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='irudia',
            field=models.TextField(),
        ),
    ]
