# Generated by Django 3.2.8 on 2021-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0010_auto_20211119_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='entrega_data',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
