# Generated by Django 3.2.8 on 2021-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0012_alter_ticket_entrega_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='entrega_data',
            field=models.DateTimeField(default='2000-01-01 00:00'),
        ),
    ]
