# Generated by Django 3.2.8 on 2021-11-19 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0013_alter_ticket_entrega_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='entrega_data',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
