# Generated by Django 3.2.8 on 2021-11-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0016_ticket_entrega_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='entrega_data',
        ),
    ]
