# Generated by Django 3.2.8 on 2021-11-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baloOkindegia', '0018_ticket_entrega_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_bezeroa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bezeroa',
        ),
    ]
