# Generated by Django 3.2.8 on 2021-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloOkindegia', '0019_auto_20211119_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='helbidea',
            field=models.TextField(default=None),
        ),
    ]
