-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 09:17:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema okindegia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema okindegia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `okindegia` DEFAULT CHARACTER SET utf8 ;
USE `okindegia` ;

-- -----------------------------------------------------
-- Table `okindegia`.`bezeroak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okindegia`.`bezeroak` ;

CREATE TABLE IF NOT EXISTS `okindegia`.`bezeroak` (
  `id_bezeroa` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefonoa` VARCHAR(9) NULL,
  PRIMARY KEY (`id_bezeroa`),
  UNIQUE INDEX `id_bezeroa_UNIQUE` (`id_bezeroa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okindegia`.`produktuak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okindegia`.`produktuak` ;

CREATE TABLE IF NOT EXISTS `okindegia`.`produktuak` (
  `id_produktua` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NULL,
  `prezioa` DOUBLE NULL,
  PRIMARY KEY (`id_produktua`),
  UNIQUE INDEX `id_produktua_UNIQUE` (`id_produktua` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okindegia`.`banatzailea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okindegia`.`banatzailea` ;

CREATE TABLE IF NOT EXISTS `okindegia`.`banatzailea` (
  `id_banatzailea` INT NOT NULL,
  `nan` VARCHAR(9) NOT NULL,
  `izena` VARCHAR(45) NULL,
  `abizena` VARCHAR(45) NULL,
  `libre_dago` BIT(1) NULL,
  PRIMARY KEY (`id_banatzailea`),
  UNIQUE INDEX `nan_UNIQUE` (`nan` ASC) VISIBLE,
  UNIQUE INDEX `id_banatzailea_UNIQUE` (`id_banatzailea` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okindegia`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okindegia`.`ticket` ;

CREATE TABLE IF NOT EXISTS `okindegia`.`ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `id_bezeroa` INT NOT NULL,
  `data` DATETIME NULL,
  `totala` DOUBLE NULL,
  `id_banatzailea` INT NOT NULL,
  PRIMARY KEY (`id_ticket`, `id_bezeroa`),
  INDEX `fk_eskaerak_bezeroak_idx` (`id_bezeroa` ASC) VISIBLE,
  INDEX `fk_ticket_banatzailea1_idx` (`id_banatzailea` ASC) VISIBLE,
  CONSTRAINT `fk_eskaerak_bezeroak`
    FOREIGN KEY (`id_bezeroa`)
    REFERENCES `okindegia`.`bezeroak` (`id_bezeroa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_banatzailea1`
    FOREIGN KEY (`id_banatzailea`)
    REFERENCES `okindegia`.`banatzailea` (`id_banatzailea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okindegia`.`ticket_lerroak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okindegia`.`ticket_lerroak` ;

CREATE TABLE IF NOT EXISTS `okindegia`.`ticket_lerroak` (
  `id_ticket` INT NOT NULL,
  `id_produktua` INT NOT NULL,
  `kantitatea` VARCHAR(45) NULL,
  `subtotala` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ticket`, `id_produktua`),
  INDEX `fk_ticket_lerroak_produktuak1_idx` (`id_produktua` ASC) VISIBLE,
  INDEX `fk_ticket_lerroak_ticket1_idx` (`id_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_lerroak_produktuak1`
    FOREIGN KEY (`id_produktua`)
    REFERENCES `okindegia`.`produktuak` (`id_produktua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_lerroak_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `okindegia`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
